### ISSUE TITLE
Language_Pad.LanguagePadCommon caused an exception

### ISSUE THREAD

**Issue by myrkvi** [ianmartinez/LangPad#1] opened 2015-09-09 12:23 UTC
Upon opening the application, I get this error message:

```
Se slutten av denne meldingen for detaljert informasjon om aktivering av 
JIT-feilsøking (Just In Time) i stedet for denne dialogboksen.

************** Unntakstekst **************
System.TypeInitializationException: Typeinitialiseringen for Language_Pad.LanguagePadCommon forårsaket et unntak. ---> System.InvalidCastException: Konvertering fra strengen 7.0 til typen Decimal er ikke gyldig.
   ved Microsoft.VisualBasic.CompilerServices.Conversions.ToDecimal(String Value, NumberFormatInfo NumberFormat)
   ved Microsoft.VisualBasic.CompilerServices.Conversions.ToDecimal(Object Value, NumberFormatInfo NumberFormat)
   ved Microsoft.VisualBasic.CompilerServices.Conversions.ToDecimal(Object Value)
   ved Language_Pad.LanguagePadCommon..cctor()
   --- Slutten på sporingen av intern unntaksstakk ---
   ved Language_Pad.ssLoading.ssLoading_Load(Object sender, EventArgs e)
   ved System.Windows.Forms.Form.OnLoad(EventArgs e)
   ved System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   ved System.Windows.Forms.Control.CreateControl()
   ved System.Windows.Forms.Control.WmShowWindow(Message& m)
   ved System.Windows.Forms.Control.WndProc(Message& m)
   ved System.Windows.Forms.Form.WmShowWindow(Message& m)
   ved System.Windows.Forms.Form.WndProc(Message& m)
   ved System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Innlastede samlinger **************
mscorlib
    Samlingsversjon: 4.0.0.0
    Win32-versjon: 4.0.30319.1026 (RTMGDR.030319-1000)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Language Pad
    Samlingsversjon: 7.0.0.0
    Win32-versjon: 7.0.0.0
    CodeBase: file:///D:/Brukere/berve280197/Language%20Pad%20Latest%20Release/Language%20Pad.exe
----------------------------------------
Microsoft.VisualBasic
    Samlingsversjon: 10.0.0.0
    Win32-versjon: 10.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Samlingsversjon: 4.0.0.0
    Win32-versjon: 4.0.30319.1026 built by: RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Samlingsversjon: 4.0.0.0
    Win32-versjon: 4.0.30319.233 built by: RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Samlingsversjon: 4.0.0.0
    Win32-versjon: 4.0.30319.1002 built by: RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Samlingsversjon: 4.0.0.0
    Win32-versjon: 4.0.30319.1001 built by: RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Runtime.Remoting
    Samlingsversjon: 4.0.0.0
    Win32-versjon: 4.0.30319.1030 (RTMGDR.030319-1000)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
Tundra
    Samlingsversjon: 2.1.0.0
    Win32-versjon: 2.1.0.0
    CodeBase: file:///D:/Brukere/berve280197/Language%20Pad%20Latest%20Release/Tundra.DLL
----------------------------------------
mscorlib.resources
    Samlingsversjon: 4.0.0.0
    Win32-versjon: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_no_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Microsoft.VisualBasic.resources
    Samlingsversjon: 10.0.0.0
    Win32-versjon: 10.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic.resources/v4.0_10.0.0.0_no_b03f5f7f11d50a3a/Microsoft.VisualBasic.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Samlingsversjon: 4.0.0.0
    Win32-versjon: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_no_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT-feilsøking **************
Når du skal aktivere JIT-feilsøking (Just In Time), må .config-filen for dette
programmet eller datamaskinen (machine.config) ha
jitDebugging-verdien angitt i delen system.windows.forms.
Programmet må også kompileres med feilsøking
aktivert.

For eksempel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Når JIT-feilsøking er aktivert, blir alle ubehandlede unntak
sendt til JIT-feilsøkingen som er registrert på datamaskinen,
i stedet for å bli behandlet av denne dialogboksen.
```

After a while I get the standard "<Application> has stopped working" message.

**Comment by ianmartinez** [comment] 2017-09-10 06:46
I know it's been years, but I've started maintaining this project again and it should be fixed in the next release. It was caused by the code the formatted the version number assuming that the decimal separator was always '.'.

**Closed as completed by ianmartinez** 2017-09-10 06:46 UTC
